server:
  port: 9002
  shutdown: graceful
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      max: 50
      min-spare: 5

spring:
  application:
    name: course-service
  lifecycle:
    timeout-per-shutdown-phase: 15s
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    username: ${MANAGEMENT_DB_USERNAME:postgres}
    password: ${MANAGEMENT_DB_PASSWORD:password}
    url: ${MANAGEMENT_DB_STRING:jdbc:postgresql://localhost:5432/management}
    hikari:
      connection-timeout: 2000 #ms
      maximum-pool-size: 5
springdoc:
  api-docs:
    path: /api-docs

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

info:
  system: schoolist


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
      show-components: always
      probes:
        enabled: true
  info:
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true
  observations:
    key-values:
      application: ${spring.application.name}